#!/usr/bin/env bash

rm public/bundle.*

{
  postcss -u autoprefixer < public/css/pace.theme.css | cleancss --skip-rebase --skip-advanced \
    --skip-aggressive-merging --skip-restructuring
  echo
  postcss -u autoprefixer < public/css/app.css | cleancss --skip-rebase --skip-advanced \
    --skip-aggressive-merging --skip-restructuring
} >> public/bundle.css

{
  uglifyjs --screw-ie8 public/js/pace.setup.js
  cat public/js/pace.min.js
  uglifyjs --screw-ie8 public/js/app.js
} >> public/bundle.js
