#!/usr/bin/env bash

mkdir -p dist/img

rm dist/*.css dist/*.js

{
  postcss -u autoprefixer < public/css/pace.theme.css | cleancss --skip-rebase --skip-advanced \
    --skip-aggressive-merging --skip-restructuring
  echo
  postcss -u autoprefixer < public/css/app.css | cleancss --skip-rebase --skip-advanced \
    --skip-aggressive-merging --skip-restructuring
} >> dist/bundle.css

{
  uglifyjs public/js/pace.setup.js
  uglifyjs public/js/pace.min.js
  uglifyjs public/js/app.js
} >> dist/bundle.js

cp -R public/favicon.ico dist
cp -R public/img/* dist/img
